spring:
  application:
    name: social-automation
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: /api
nst-browser:
  api-key: ${NST_BROWSER_API_KEY:cad3ac5c-af11-4b17-938f-8ecfc58267e2}
