spring:
  datasource:
    url: jdbc:postgresql://postgres_kayleigh:5432/myapp_db
    username: myapp_user
    password: supersecretpassword
    driver-class-name: org.postgresql.Driver
nst-browser:
  host: 194.163.164.118
  port: 8000
  api-key: f48ec8e6-4714-4bfe-a3bc-2964ce38019f
  url: http://194.163.164.118:8000/api/v2
  headless: false
