spring:
  datasource:
    url: jdbc:postgresql://localhost:5449/myapp_db
    username: myapp_user
    password: supersecretpassword
    driver-class-name: org.postgresql.Driver
nst-browser:
  host: localhost
  port: 8000
  api-key: 1c9d7a46-4bf1-43c6-a532-3d92b7966852
  url: http://localhost:8000/api/v2
  headless: true