spring:
  datasource:
    url: jdbc:postgresql://localhost:5449/myapp_db
    username: myapp_user
    password: supersecretpassword
    driver-class-name: org.postgresql.Driver
nst-browser:
  host: localhost
  port: 8848
  api-key: 7ffc59e4-8b42-4db8-b0c6-c996c4570360
  url: http://localhost:8848/api/v2
  headless: false