spring:
  application:
    name: social-automation
  profiles:
    active: dev-nst-docker
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: /api
app:
  props:
    accounts-per-proxy: 5
    accounts-password: Qwerty1234@