spring:
  datasource:
    url: jdbc:postgresql://localhost:5449/myapp_db
    username: myapp_user
    password: supersecretpassword
    driver-class-name: org.postgresql.Driver
nst-browser:
  host: localhost
  port: 8848
  api-key: 60f2f27a-8003-46df-b64b-3a466f352917
  url: http://localhost:8848/api/v2
  headless: false
sad-captcha:
  api-key: 3fdecf44b2eaa75fdb3e3b3713c75a47