spring:
  datasource:
    url: jdbc:postgresql://localhost:5449/myapp_db
    username: myapp_user
    password: supersecretpassword
    driver-class-name: org.postgresql.Driver
nst-browser:
  host: localhost
  port: 8848
  api-key: 99aafaf5-f247-4df6-846d-7e1b21008214
  url: http://localhost:8848/api/v2
  headless: false