spring:
  datasource:
    url: jdbc:postgresql://localhost:5449/myapp_db
    username: myapp_user
    password: supersecretpassword
    driver-class-name: org.postgresql.Driver
nst-browser:
  host: localhost
  port: 8000
  api-key: de2bc73d-8c37-4762-a5a8-cc2ebf0138df
  url: http://localhost:8000/api/v2
  headless: true