spring:
  application:
    name: social-automation
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
nst-browser:
  api-key: 7ffc59e4-8b42-4db8-b0c6-c996c4570360
  url: http://nstbrowserless_00:8848/api/v2
