spring:
  application:
    name: social-automation
  datasource:
    url: jdbc:postgresql://postgres_kayleigh:5432/myapp_db
    username: myapp_user
    password: supersecretpassword
    driver-class-name: org.postgresql.Driver
nst-browser:
  host: 194.163.164.118
  port: 8000
  api-key: f6e76125-1771-48d6-94de-1d03a685884d
  url: http://194.163.164.118:8000/api/v2
  headless: false
