spring:
  application:
    name: social-automation
  datasource:
    url: jdbc:postgresql://postgres_kayleigh:5432/myapp_db
    username: myapp_user
    password: supersecretpassword
    driver-class-name: org.postgresql.Driver
nst-browser:
  host: nstbrowserless_00
  port: 8848
  api-key: f6e76125-1771-48d6-94de-1d03a685884d
  url: http://nstbrowserless_00:8848/api/v2
  headless: false
